# Generated by Django 2.2.4 on 2020-10-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregApp', '0002_auto_20201015_1512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
